/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author 666
 */
public class GUIControleFinanceiro extends javax.swing.JFrame {

    /**
     * Creates new form GUIControleFinanceiro
     */
    public GUIControleFinanceiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblReceitas = new javax.swing.JTable();
        jlblSuasReceitas = new javax.swing.JLabel();
        jlblSuasDespesas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblDespesas = new javax.swing.JTable();
        jlblSaldoMensal = new javax.swing.JLabel();
        jtfSaldoMensal = new javax.swing.JTextField();
        jlblDicasDoQFazer = new javax.swing.JLabel();
        jlblVoltar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(7, 67, 152));

        jtblReceitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Salário", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"FIIs", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Ações", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Outros", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"TOTAL", null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", "ANUAL"
            }
        ));
        jScrollPane1.setViewportView(jtblReceitas);

        jlblSuasReceitas.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jlblSuasReceitas.setText("Suas receitas");

        jlblSuasDespesas.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jlblSuasDespesas.setText("Suas despesas");

        jtblDespesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Aluguel", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"IPVA", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"IPTU", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Luz", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Água", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Internet", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Alimentos", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Transporte", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Combustível", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Outros", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"TOTAL", null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", "ANUAL"
            }
        ));
        jScrollPane2.setViewportView(jtblDespesas);

        jlblSaldoMensal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblSaldoMensal.setText("Seu saldo mensal:");

        jlblDicasDoQFazer.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jlblDicasDoQFazer.setText("Dicas do que fazer com seu saldo?");

        jlblVoltar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jlblVoltar.setText("VOLTAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlblSaldoMensal)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfSaldoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblDicasDoQFazer)
                        .addGap(29, 29, 29)))
                .addGap(246, 246, 246))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jlblSuasReceitas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(jlblSuasDespesas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblVoltar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblVoltar)
                .addGap(33, 33, 33)
                .addComponent(jlblSuasReceitas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jlblSuasDespesas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSaldoMensal)
                    .addComponent(jtfSaldoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlblDicasDoQFazer)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIControleFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIControleFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIControleFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIControleFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIControleFinanceiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlblDicasDoQFazer;
    private javax.swing.JLabel jlblSaldoMensal;
    private javax.swing.JLabel jlblSuasDespesas;
    private javax.swing.JLabel jlblSuasReceitas;
    private javax.swing.JLabel jlblVoltar;
    private javax.swing.JTable jtblDespesas;
    private javax.swing.JTable jtblReceitas;
    private javax.swing.JTextField jtfSaldoMensal;
    // End of variables declaration//GEN-END:variables
}
