/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author 666
 */
public class GUILogin extends javax.swing.JFrame implements InternalFrameListener {

    /**
     * Creates new form GUIPrincipal
     */
    public GUILogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBackgroundLogin = new javax.swing.JPanel();
        jlblUsuario = new javax.swing.JLabel();
        jlblSenha = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jlblImagemLogin = new javax.swing.JLabel();
        jbtnLogar = new javax.swing.JButton();
        jbtnEsqueciSenha = new javax.swing.JButton();
        jbtnCadastrarConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBackgroundLogin.setBackground(new java.awt.Color(7, 67, 152));

        jlblUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jlblUsuario.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jlblUsuario.setText("Usuário");

        jlblSenha.setBackground(new java.awt.Color(204, 204, 204));
        jlblSenha.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblSenha.setForeground(new java.awt.Color(204, 204, 204));
        jlblSenha.setText("Senha");

        jpfSenha.setText("jPasswordField1");

        jlblImagemLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\T-Gamer\\Desktop\\MONEASY PROJETO INTEGRADOR\\logoVazadoLogin.png")); // NOI18N

        jbtnLogar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbtnLogar.setText("Entrar");
        jbtnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogarActionPerformed(evt);
            }
        });

        jbtnEsqueciSenha.setIcon(new javax.swing.ImageIcon("C:\\Users\\T-Gamer\\Desktop\\MONEASY PROJETO INTEGRADOR\\EsqueciMinhaSenhaBotao.png")); // NOI18N
        jbtnEsqueciSenha.setBorder(null);

        jbtnCadastrarConta.setIcon(new javax.swing.ImageIcon("C:\\Users\\T-Gamer\\Desktop\\MONEASY PROJETO INTEGRADOR\\NaoCadastradoBotao.png")); // NOI18N
        jbtnCadastrarConta.setBorder(null);
        jbtnCadastrarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadastrarContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBackgroundLoginLayout = new javax.swing.GroupLayout(jpBackgroundLogin);
        jpBackgroundLogin.setLayout(jpBackgroundLoginLayout);
        jpBackgroundLoginLayout.setHorizontalGroup(
            jpBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBackgroundLoginLayout.createSequentialGroup()
                .addGroup(jpBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBackgroundLoginLayout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jlblUsuario))
                    .addGroup(jpBackgroundLoginLayout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(jlblSenha))
                    .addGroup(jpBackgroundLoginLayout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(jbtnLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBackgroundLoginLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jlblImagemLogin))
                    .addGroup(jpBackgroundLoginLayout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addGroup(jpBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnCadastrarConta)
                            .addGroup(jpBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfUsuario)
                                .addComponent(jpfSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpBackgroundLoginLayout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(jbtnEsqueciSenha)))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jpBackgroundLoginLayout.setVerticalGroup(
            jpBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBackgroundLoginLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jlblImagemLogin)
                .addGap(55, 55, 55)
                .addComponent(jlblUsuario)
                .addGap(18, 18, 18)
                .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jlblSenha)
                .addGap(18, 18, 18)
                .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jbtnLogar)
                .addGap(24, 24, 24)
                .addComponent(jbtnEsqueciSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCadastrarConta)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackgroundLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackgroundLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnLogarActionPerformed
        boolean flagCadastrar = false;
    private void jbtnCadastrarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadastrarContaActionPerformed
        if (!flagCadastrar) {
            GUICadastrarConta gcc = new GUICadastrarConta();
            jpBackgroundLogin.add(gcc);
            gcc.setVisible(true);
            flagCadastrar = true;
            gcc.addInternalFrameListener(this);
        }
    }//GEN-LAST:event_jbtnCadastrarContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCadastrarConta;
    private javax.swing.JButton jbtnEsqueciSenha;
    private javax.swing.JButton jbtnLogar;
    private javax.swing.JLabel jlblImagemLogin;
    private javax.swing.JLabel jlblSenha;
    private javax.swing.JLabel jlblUsuario;
    private javax.swing.JPanel jpBackgroundLogin;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent e) {
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent e) {
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent e) {
        if(e.getInternalFrame() instanceof GUICadastrarConta){
            flagCadastrar = true;
        }
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent e) {
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent e) {
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent e) {
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent e) {
    }
}
