/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author 666
 */
public class GUITelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUITelaPrincipal
     */
    public GUITelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTelaPrincipal = new javax.swing.JPanel();
        jlblPiggyBank = new javax.swing.JLabel();
        jlblWelcomeUsername = new javax.swing.JLabel();
        jbtnControleFinanceiro = new javax.swing.JButton();
        jbtnDicasDeInvestimentos = new javax.swing.JButton();
        jbtnMinhasAnotacoes = new javax.swing.JButton();
        jbtnLogoff = new javax.swing.JButton();
        jlblProximosVencimentos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlProximosVencimentos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpTelaPrincipal.setBackground(new java.awt.Color(7, 67, 152));

        jlblPiggyBank.setIcon(new javax.swing.ImageIcon("C:\\Users\\T-Gamer\\Desktop\\MONEASY PROJETO INTEGRADOR\\Piggy bank-amico.png")); // NOI18N

        jlblWelcomeUsername.setBackground(new java.awt.Color(204, 204, 204));
        jlblWelcomeUsername.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jlblWelcomeUsername.setForeground(new java.awt.Color(204, 204, 204));
        jlblWelcomeUsername.setText("Bem-vindo(a), [username]!");

        jbtnControleFinanceiro.setBackground(new java.awt.Color(7, 114, 246));
        jbtnControleFinanceiro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbtnControleFinanceiro.setForeground(new java.awt.Color(204, 204, 204));
        jbtnControleFinanceiro.setText("Meu controle financeiro");

        jbtnDicasDeInvestimentos.setBackground(new java.awt.Color(7, 114, 246));
        jbtnDicasDeInvestimentos.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbtnDicasDeInvestimentos.setForeground(new java.awt.Color(204, 204, 204));
        jbtnDicasDeInvestimentos.setText("Dicas de Investimentos");

        jbtnMinhasAnotacoes.setBackground(new java.awt.Color(7, 114, 246));
        jbtnMinhasAnotacoes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbtnMinhasAnotacoes.setForeground(new java.awt.Color(204, 204, 204));
        jbtnMinhasAnotacoes.setText("Minhas anotações");

        jbtnLogoff.setBackground(new java.awt.Color(7, 114, 246));
        jbtnLogoff.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbtnLogoff.setForeground(new java.awt.Color(204, 204, 204));
        jbtnLogoff.setText("Sair");
        jbtnLogoff.setBorder(null);

        jlblProximosVencimentos.setBackground(new java.awt.Color(204, 204, 204));
        jlblProximosVencimentos.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlblProximosVencimentos.setText("Próximos vencimentos");

        jlProximosVencimentos.setBackground(new java.awt.Color(7, 114, 246));
        jlProximosVencimentos.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jlProximosVencimentos.setForeground(new java.awt.Color(204, 204, 204));
        jlProximosVencimentos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Conta de Água   | 05/04/22", "Conta de Luz      | 05/04/22", "Aluguel                | 10/04/22", "Internet               | 11/04/22" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlProximosVencimentos);

        javax.swing.GroupLayout jpTelaPrincipalLayout = new javax.swing.GroupLayout(jpTelaPrincipal);
        jpTelaPrincipal.setLayout(jpTelaPrincipalLayout);
        jpTelaPrincipalLayout.setHorizontalGroup(
            jpTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTelaPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jpTelaPrincipalLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jlblPiggyBank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(jpTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTelaPrincipalLayout.createSequentialGroup()
                        .addGroup(jpTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtnControleFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(jbtnDicasDeInvestimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnMinhasAnotacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTelaPrincipalLayout.createSequentialGroup()
                        .addGroup(jpTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jlblProximosVencimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(144, 144, 144))))
            .addGroup(jpTelaPrincipalLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jlblWelcomeUsername)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTelaPrincipalLayout.setVerticalGroup(
            jpTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnLogoff)
                .addGap(69, 69, 69)
                .addComponent(jlblWelcomeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jbtnControleFinanceiro)
                .addGroup(jpTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTelaPrincipalLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jbtnDicasDeInvestimentos)
                        .addGap(50, 50, 50)
                        .addComponent(jbtnMinhasAnotacoes)
                        .addGap(64, 64, 64)
                        .addComponent(jlblProximosVencimentos)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addGap(91, 91, 91))
                    .addGroup(jpTelaPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblPiggyBank)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnControleFinanceiro;
    private javax.swing.JButton jbtnDicasDeInvestimentos;
    private javax.swing.JButton jbtnLogoff;
    private javax.swing.JButton jbtnMinhasAnotacoes;
    private javax.swing.JList<String> jlProximosVencimentos;
    private javax.swing.JLabel jlblPiggyBank;
    private javax.swing.JLabel jlblProximosVencimentos;
    private javax.swing.JLabel jlblWelcomeUsername;
    private javax.swing.JPanel jpTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
